import type { Metadata } from "next"; // Importa o tipo Metadata do Next.js
import { Geist, Geist_Mono } from "next/font/google"; // Importa as fontes do Google via Next.js
import "./globals.css"; // Importa o arquivo global de estilos

// Configuração das fontes Geist Sans e Geist Mono
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Definição dos metadados da aplicação
export const metadata: Metadata = {
  title: "Calculadora", // Define o título da aba
  description: "Generated by create next app", // Descrição da aplicação
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
